achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"bona1000", "bona2500", "bona5000", "bona10000", "ribbit", "ribbit1000", "ribbit2500", "ribbit5000", "ribbit10000"},
	achievements = {
		{
			id = "bona1000",
			name = "Fetching Scores",
			description = "Score 1,000 points",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "bona2500",
			name = "Bork bork bork",
			description = "Score 2,500 points",
			isSecret = false,
			progressMax = 2500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "bona5000",
			name = "Bona Fide Bona Fido",
			description = "Score 5,000 points",
			isSecret = false,
			progressMax = 5000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "bona10000",
			name = "After No Life",
			description = "Score 10,000 points",
			isSecret = false,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "ribbit",
			name = "Rib-bit!",
			description = "Unlock Rib-bit",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "ribbit1000",
			name = "Hop,",
			description = "Score 1,000 points as Rib-bit",
			isSecret = true,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "ribbit2500",
			name = "skip,",
			description = "Score 2,500 points as Rib-bit",
			isSecret = true,
			progressMax = 2500,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "ribbit5000",
			name = "and",
			description = "Score 5,000 points as Rib-bit",
			isSecret = true,
			progressMax = 5000,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "ribbit10000",
			name = "a jump.",
			description = "Score 10,000 points as Rib-bit",
			isSecret = true,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 0,
		},
	}
}